const newsData = [
  {
    id: 'news_policy2025',
    title_zh: '💰 零关税商品扩至74%税目',
    title_en: '💰 Zero-Tariff Goods Expand to 74%',
    date: '2025-12-28',
    content_zh: '封关运作后，零关税商品范围由21%跃升至74%，覆盖约6600个税目，企业进口成本节省约20%。',
    content_en: 'After closure, zero-tariff goods expanded from 21% to 74%, covering 6,600 tax items, saving companies ~20% import costs.',
    detail_zh: '海南自贸港封关运作超十日，多项升级版政策相继落地。零关税商品税目比例从封关前的1900个扩大至约6600个，约占全部商品税目的74%。享惠主体从独立法人扩展到各类企事业单位，政策门槛更低。加工增值达30%的货物可免关税销往内地。首批零关税科研设备已投入使用，北大口腔医院三亚医院进口设备总值100万元，免税额度达12%。海南炼化与伟达化工达成合作，开启从原料到加工到增值的合作链条。',
    detail_en: 'Over 10 days after Hainan FTP closure, multiple upgraded policies have been implemented. Zero-tariff goods expanded from 1,900 to 6,600 tax items, covering 74% of all categories. Eligible entities expanded from independent legal persons to various institutions. Goods with 30% value-added can enter mainland duty-free. First batch of zero-tariff research equipment deployed at Peking University Dental Hospital Sanya, with 12% tax savings on 1 million yuan equipment.',
    tags_zh: ['零关税', '政策升级', '封关运作'],
    tags_en: ['Zero Tariff', 'Policy Upgrade', 'Closure']
  },
  {
    id: 'news_investment2025',
    title_zh: '📈 前三季度外资增长超40%',
    title_en: '📈 Q1-Q3 FDI Up 40%+',
    date: '2025-12-24',
    content_zh: '2025年前三季度，海南新设外资企业1513家，实际使用外资同比增长超40%，开放水平持续提升。',
    content_en: 'In Q1-Q3 2025, Hainan added 1,513 foreign enterprises, with actual FDI up 40%+ YoY, opening level continues rising.',
    detail_zh: '2025年前三季度，海南13个重点园区实现营收19924.51亿元，增长4.1%。新设外资企业1513家，实际使用外资同比增长超四成。服务贸易进出口总额407.19亿元，增长26.2%，其中服务出口总额272.09亿元，增长60.7%。前10个月，全省新增对外投资备案企业296家，同比增长43%；实际对外投资额31.7亿美元，同比增长42.6%。176个国家和地区在琼投资，经济外向度提高到35%。海南成为吸引全球优质资源要素的强磁场。',
    detail_en: 'In Q1-Q3 2025, Hainan\'s 13 key parks achieved revenue of 1,992.451 billion yuan, up 4.1%. 1,513 new foreign enterprises established, with actual FDI up over 40% YoY. Service trade totaled 40.719 billion yuan, up 26.2%, with service exports at 27.209 billion yuan, up 60.7%. In first 10 months, 296 new outbound investment enterprises registered, up 43%; actual outbound investment $3.17 billion, up 42.6%. 176 countries/regions invested in Hainan, economic openness reached 35%.',
    tags_zh: ['外资', '投资', '经济增长'],
    tags_en: ['FDI', 'Investment', 'Economic Growth']
  },
  {
    id: 'news_industry2025',
    title_zh: '🚀 三大未来产业加速发展',
    title_en: '🚀 Three Future Industries Accelerate',
    date: '2025-12-20',
    content_zh: '南繁种业产值突破180亿元，海洋生产总值突破2700亿元，商业航天发射场具备高密度发射能力。',
    content_en: 'Nanfan seed industry output exceeded 18 billion yuan, marine GDP topped 270 billion yuan, commercial spaceport ready for high-frequency launches.',
    detail_zh: '海南加快构建"4+3+3"现代化产业体系。三大未来产业蓬勃发展：南繁种业产值突破180亿元，致力打造保障国家粮食安全的"种业硅谷"；海洋生产总值突破2700亿元，向深海科技、海洋药物等蓝色经济进军；全国首个商业航天发射场在文昌建成，具备高密度常态化发射能力，带动"火箭链、卫星链、数据链"产业集群发展。星际荣耀已在文昌建起中国首家运载火箭"复用工厂"。封关带来的国际交流便利和先进设备、技术进口成本降低，为前沿领域研究与产业化注入强劲动力。',
    detail_en: 'Hainan accelerates building "4+3+3" modern industrial system. Three future industries thrive: Nanfan seed industry output exceeds 18 billion yuan, building "Seed Silicon Valley" for national food security; marine GDP tops 270 billion yuan, advancing deep-sea tech and marine pharmaceuticals; China\'s first commercial spaceport in Wenchang operational with high-frequency launch capability, driving rocket-satellite-data chain clusters. Interstellar Glory built China\'s first reusable rocket factory in Wenchang. Closure brings international exchange facilitation and lower import costs for advanced equipment.',
    tags_zh: ['未来产业', '种业', '航天', '海洋'],
    tags_en: ['Future Industries', 'Seeds', 'Aerospace', 'Marine']
  },
  {
    id: 'news_closure1',
    title_zh: '🎯 历史性时刻！海南全岛封关正式启动',
    title_en: '🎯 Historic Moment! Island-wide Closure Launched',
    date: '2025-12-18',
    content_zh: '2025年12月18日，海南自由贸易港正式启动全岛封关，中国对外开放迎来里程碑时刻。3万多平方公里的海南岛正式成为海关监管特殊区域。',
    content_en: 'On December 18, 2025, Hainan Free Trade Port officially launched island-wide closure. The 30,000+ sq km island became a special customs supervision zone.',
    detail_zh: '2025年12月18日，海南自由贸易港正式启动全岛封关，中国对外开放迎来里程碑时刻。3万多平方公里的海南岛正式成为海关监管特殊区域，"一线放开、二线管住、岛内自由"的新篇章就此开启。封关运作标志着海南自贸港建设从"逐步探索"迈入"全面运行"新阶段，成为引领我国新时代对外开放的重要门户。封关首日，洋浦港、三亚凤凰国际机场等口岸集中进口原油、医疗设备、航材、食品原料等"零关税"货物，总货值超5亿元。',
    detail_en: 'On December 18, 2025, Hainan FTP officially launched island-wide closure operation, marking a milestone in China\'s opening-up. The 30,000+ sq km island officially became a special customs supervision zone, opening a new chapter of "first-line liberalization, second-line management, free flow within the island". On closure day, Yangpu Port and Sanya Phoenix Airport imported crude oil, medical equipment, aviation materials with total value exceeding 500 million yuan.',
    tags_zh: ['封关', '自贸港', '开放'],
    tags_en: ['Closure', 'FTP', 'Opening']
  },
  {
    id: 'news1',
    title_zh: '📈 人才个税政策延续',
    title_en: '📈 Talent Tax Extended',
    date: '2025-12-15',
    content_zh: '高端人才和紧缺人才个人所得税实际税负超过15%的部分免征政策延续至2035年。',
    content_en: 'High-end talent tax benefits extended to 2035, exempting excess above 15%.',
    detail_zh: '财政部、税务总局发布公告，明确海南自贸港高端人才和紧缺人才个人所得税优惠政策延续至2035年12月31日。对在海南自由贸易港工作的高端人才和紧缺人才，其个人所得税实际税负超过15%的部分予以免征。这一政策将大大增强海南对人才的吸引力。',
    detail_en: 'The Ministry of Finance announced the extension of preferential individual income tax policies for high-end and urgently-needed talent in Hainan FTP until December 31, 2035, exempting the portion exceeding 15% actual tax burden.',
    tags_zh: ['个税', '人才', '优惠政策'],
    tags_en: ['Tax', 'Talent', 'Benefits']
  },
  {
    id: 'news2',
    title_zh: '🎉 总书记考察海南',
    title_en: '🎉 President Visit',
    date: '2025-12-10',
    content_zh: '习近平总书记考察海南，强调要加快建设具有世界影响力的中国特色自由贸易港。',
    content_en: 'President Xi inspected Hainan, emphasizing building a world-class free trade port.',
    detail_zh: '习近平总书记在海南考察时强调，要解放思想、开拓创新，团结奋斗、攻坚克难，加快建设具有世界影响力的中国特色自由贸易港。总书记的重要讲话为海南自贸港建设指明了方向，提供了根本遵循。海南将牢记嘱托，勇担使命，全力推进自贸港建设。',
    detail_en: 'During his inspection in Hainan, President Xi emphasized the need to emancipate the mind, innovate, unite in struggle, and overcome difficulties to accelerate the construction of a Chinese-characteristic free trade port with world influence.',
    tags_zh: ['考察', '自贸港', '发展'],
    tags_en: ['Visit', 'FTP', 'Development']
  },
  {
    id: 'news3',
    title_zh: '💼 前11月外贸大增',
    title_en: '💼 Trade Growth',
    date: '2025-12-05',
    content_zh: '2025年前11月，海南外贸进出口总额同比增长19.4%，展现强劲发展态势。',
    content_en: 'Jan-Nov 2025 trade up 19.4% YoY, showing strong growth momentum.',
    detail_zh: '海关统计数据显示，2025年前11月，海南外贸进出口总额达到1850亿元，同比增长19.4%。其中，出口增长22.1%，进口增长17.8%。这一数据充分说明了海南自贸港政策红利正在不断释放，营商环境持续优化，吸引了越来越多的企业在海南开展业务。',
    detail_en: 'Customs statistics show that from January to November 2025, Hainan\'s total import and export volume reached 185 billion yuan, up 19.4% year-on-year, with exports up 22.1% and imports up 17.8%.',
    tags_zh: ['外贸', '数据', '增长'],
    tags_en: ['Trade', 'Data', 'Growth']
  },
  {
    id: 'news4',
    title_zh: '🏢 新增企业突破10万家',
    title_en: '🏢 100K+ New Enterprises',
    date: '2025-11-28',
    content_zh: '2025年海南新增市场主体突破10万家，市场活力持续增强。',
    content_en: '100,000+ new market entities in 2025, vitality continues to grow.',
    detail_zh: '截至2025年11月底，海南全省新增市场主体超过10万家，同比增长15.3%。其中，新增企业6.8万家，个体工商户3.2万家。市场主体的快速增长，充分体现了海南自贸港对企业的强大吸引力和良好的营商环境。',
    detail_en: 'As of end of November 2025, over 100,000 new market entities were added in Hainan, up 15.3% YoY, including 68,000 enterprises and 32,000 individual businesses.',
    tags_zh: ['企业', '注册', '市场主体'],
    tags_en: ['Enterprise', 'Registration', 'Market']
  },
  {
    id: 'news5',
    title_zh: '✈️ 开放第七航权',
    title_en: '✈️ 7th Freedom Rights',
    date: '2020-06-10',
    content_zh: '海南自贸港试点开放第七航权，这是我国民航史上最大力度航权开放。',
    content_en: 'Hainan FTP pilots 7th freedom rights, China\'s highest-level aviation opening.',
    detail_zh: '民航局印发《海南自由贸易港试点开放第七航权实施方案》，明确鼓励、支持外航在海南经营客、货运第七航权。这是我国民航首次同时试点开放客运和货运第七航权，是我国在航权方面的最高水平开放，也是世界范围内自贸港航权开放的最高水平。第七航权指完全第三国运输权，外国航空公司可在境外两国间载运客货，而不用返回本国。2025年12月，三亚至布拉格航线成为海南自贸港首条投入运营的第七航权航线。',
    detail_en: 'CAAC issued the Implementation Plan for Pilot Opening of 7th Freedom Rights in Hainan FTP, encouraging foreign airlines to operate passenger and cargo 7th freedom rights in Hainan. This is China\'s first simultaneous pilot opening of both passenger and cargo 7th freedom rights, representing the highest level of aviation rights opening in China and globally among free trade ports. The 7th freedom right allows foreign airlines to carry passengers and cargo between two foreign countries without returning to their home country. In December 2025, the Sanya-Prague route became Hainan FTP\'s first operational 7th freedom rights route.',
    tags_zh: ['航权', '开放', '民航'],
    tags_en: ['Aviation Rights', 'Opening', 'Aviation']
  }
];
